# Generated by Django 2.2.6 on 2021-10-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome_completo', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=11)),
                ('data_inicio', models.DateTimeField(max_length=30)),
                ('data_final', models.DateTimeField(max_length=30)),
                ('plano_escolhido', models.CharField(max_length=10)),
                ('data_criado', models.DateTimeField(auto_now_add=True)),
                ('data_editado', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
