# Generated by Django 2.2.6 on 2022-04-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cpf',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='data_final',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='plano_escolhido',
            field=models.CharField(max_length=50),
        ),
    ]
