# Generated by Django 2.2.6 on 2022-05-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_auto_20220430_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='acesso_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome_acesso', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=13)),
                ('data_inicio', models.DateTimeField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
