# Generated by Django 2.2.6 on 2022-05-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_acesso_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acesso_cliente',
            old_name='cpf',
            new_name='cpf_acesso',
        ),
        migrations.RenameField(
            model_name='acesso_cliente',
            old_name='data_inicio',
            new_name='data_acesso',
        ),
    ]
