# Generated by Django 2.2.6 on 2022-05-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_auto_20220507_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='quantidade_aulas',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
