# Generated by Django 2.2.6 on 2022-05-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0006_usuarios_quantidade_aulas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='ultimo_acesso',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
