# Generated by Django 2.2.6 on 2022-05-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0008_auto_20220508_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='ultimo_acesso',
            new_name='acesso_anterior',
        ),
    ]
