# Generated by Django 2.2.6 on 2022-05-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0009_auto_20220508_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='acesso_cliente',
            name='status_acesso',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
