# Generated by Django 2.2.6 on 2022-06-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0010_acesso_cliente_status_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='data_inicio',
            field=models.CharField(max_length=30),
        ),
    ]
