# Generated by Django 2.2.6 on 2022-06-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0011_auto_20220607_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='data_criado',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='data_editado',
            field=models.CharField(max_length=30),
        ),
    ]
