# Generated by Django 2.2.6 on 2022-06-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0012_auto_20220607_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='acesso_anterior',
            field=models.CharField(max_length=30),
        ),
    ]
