# Generated by Django 2.2.6 on 2022-06-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0013_auto_20220607_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso_cliente',
            name='data_acesso',
            field=models.CharField(max_length=30),
        ),
    ]
