# Generated by Django 2.2.6 on 2022-06-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0014_auto_20220607_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default=2, max_length=60, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='username',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
