# Generated by Django 2.2.6 on 2022-06-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0015_auto_20220610_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='username',
        ),
    ]
