# Generated by Django 2.2.6 on 2022-06-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0018_remove_usuarios_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia_adm',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
