# Generated by Django 2.2.6 on 2022-06-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0021_academia_adm_has_module_perms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academia_adm',
            old_name='has_module_perms',
            new_name='is_admin',
        ),
    ]
