# Generated by Django 2.2.6 on 2022-06-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0023_academia_adm_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='quantidade_aulas',
            field=models.IntegerField(max_length=3),
        ),
    ]
