# Generated by Django 2.2.6 on 2022-06-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0024_auto_20220617_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='quantidade_aulas',
            field=models.IntegerField(),
        ),
    ]
