# Generated by Django 2.2.6 on 2021-10-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(max_length=255)),
                ('quantidade_aulas', models.CharField(max_length=3)),
                ('valor', models.CharField(max_length=6)),
                ('data_criado', models.DateTimeField(auto_now_add=True)),
                ('data_editado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
