# Generated by Django 2.2.6 on 2022-06-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='quantidade_aulas',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='planos',
            name='valor',
            field=models.IntegerField(max_length=6),
        ),
    ]
