# Generated by Django 2.2.6 on 2022-07-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planos', '0002_auto_20220617_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='count_aluno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planos',
            name='quantidade_aulas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planos',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
