# Generated by Django 2.2.6 on 2022-07-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planos', '0003_auto_20220706_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='alunos_ativos',
            field=models.IntegerField(default=0),
        ),
    ]
