# Generated by Django 2.2.6 on 2022-07-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planos', '0004_planos_alunos_ativos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='nome_plano',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
